# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68ec05d4e08ca488a7413a67c17ccb78d14a620f24a5cc4e6dc322e66113e9d5d0ded9ccb82f3a392c07717f4dd86566152bcba64ae81f4076aeaa8593dbe831

test:
  secret_key_base: ab6c8f4aab7db834eb8058594a341f6d8b90b18d742d7d5b60107869dc2b537597a91f3bd32292b55cc4eb25e552217c37690b35462587e7fabc54be246c0b07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
